language: cpp
compiler:
  - gcc
script:
  - g++ -ohello -lboost_unit_test_framework tests/hello.cpp
  - ./tests/hello

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev