name: Build and deploy docs
on:
  pull_request:
    branches:
      - 'doc/**'
      - 'docs/**'
    tags:
      - "*"
  push:
    branches:
      - main
    tags:
      - "*"

#on:
#  schedule:
#    - cron: 0 0 * * MON

env:
  CONDA: /local/tmp/conda3/

jobs:
  build-docs:
    name: Build docs
    runs-on: self-hosted,baldur
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Setup environment
        run: echo "/usr/local/cuda-11.8/bin" > $GITHUB_PATH
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: kbmod_docs
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build KBMoD
        run: |
          python -m pip install .[docs]
      - name: Build docs
        run: |
          mkdir docs/
          sphinx-build -b html docs/source docs/build/
      - name: Deploy docs
        if: !startsWith(github.event.head_commit.message, '[deploy_docs]')
        run : |
          mv docs/build/ /epyc/users/kbmod/public_html

