name: PR tests
on:
  pull_request:
    branches:
      - main
    tags:
      - "*"
  push:
    branches:
      - main
    tags:
      - "*"

env:
  CONDA: /local/tmp/conda3/

jobs:
  test-fiducial:
    name:  In kbmod_ci env.
    runs-on: [self-hosted, bendis]
    strategy:
      fail-fast: true
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Setup environment
        run: echo "/usr/local/cuda-12/bin" > $GITHUB_PATH
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: kbmod_ci
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
        # Run linters before attempting to compile and install
        # the package, faster fails.
      - name: Linter
        uses: psf/black@stable
        with:
          jupyter: true
      - name: Build KBMoD
        run: |
          python -m pip install .
      - name: Run tests
        run: |
          cd tests
          python -m unittest -b
          cd ..
