name: test_build
on:
  push:
    branches:
      - ci
      
env:
  CONDA: /astro/users/kbmod/miniconda3
  
jobs:
  test-build:
    name: Test build
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Setup environment
        run: |
          echo "/usr/local/cuda-11.8/bin" > $GITHUB_PATH
          echo "~/.local/bin/" >> $GITHUB_PATH
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: kbmod_tests
          python-version: '3.10'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # for some reason we can't use submodule here because
        # checkout action dosn't detect the correct git
        # submodules: recursive
      - name: Build KBMoD
        run: |
          ls -al
          git --version
          # We skip this to fail early for now
          # git init
          git status
          git submodule init
          git submodule update
          python -m pip install .
