name: test_build
on:
  push:
    branches:
      - ci
      
env:
  CONDA: /home/ubuntu/miniconda3
  
jobs:
  test-build:
    name: Test build
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: kbmod_build_test
          python-version: '3.10'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build KBMoD
        run: |
          python -m pip install .
