name: test_build
on:
  push:
    branches:
      - ci
      
env:
  CONDA: /astro/users/kbmod/miniconda3
  
jobs:
  test-build:
    name: Test build
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Setup environment
        run: echo "/usr/local/cuda-11.8/bin" > $GITHUB_PATH
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: kbmod_tests
          python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build KBMoD
        run: |
          python -m pip install .
      - name: Linter
        run: |
          black --check src
      - name: Run tests
        run: |
          python -m unittest tests/* -b
          
          
          
      
